# Generated by Django 4.2 on 2023-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Description', models.CharField(max_length=120)),
                ('Candidateid', models.IntegerField()),
                ('CandidateName', models.CharField(max_length=60)),
                ('Date', models.DateTimeField()),
                ('LocationName', models.CharField(max_length=60)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
