# Generated by Django 4.2 on 2023-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='Date',
            field=models.CharField(max_length=60),
        ),
    ]
