# Generated by Django 4.2 on 2023-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_sessions', '0002_alter_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
